### ISSUE TITLE
How do I get Blender and Cargo to detect `blender_bevy_toolkit` on Windows?

### ISSUE THREAD

**Issue by Joe23232** [sdfgeoff/blender_bevy_toolkit#9]
Hey man.

So I am on Windows 10,  I ONLY copied the `blender_bevy_toolkit` (from your entire git project folder) inside `C:\Program Files\Blender Foundation\Blender 2.93\2.93\scripts\addons`

In regards to Blender, it doesn't seem to quite pick up this extension. So I suppose I have to manually install it? If I go to addons and click on the `Install` button, then if I navigate inside the extension's folder:

![image](https://user-images.githubusercontent.com/34926497/131240908-47f067c0-5767-42ce-9c80-19dea1506436.png)

Which file am I installing this from?

---

In regards to `cargo.toml` file when I added this:

```toml
[dependencies]
blender_bevy_toolkit = {path="C:\Program Files\Blender Foundation\Blender 2.93\2.93\scripts\addons\blender_bevy_toolkit"}
```

it fails to pick it up. Now I know that it contains a bunch of `py` scripts, however according to your instrunctions I am supposed to do this:

```toml
[dependencies]
blender_bevy_toolkit = {path="../blender_bevy_toolkit"}
```

I change the `path` to match where the current path of `blender_bevy_toolkit` exists.

Do you know how would I fix this mate?
